### ISSUE TITLE
Allow single context entity for track methods

### ISSUE THREAD

**Issue by mscwilson** [snowplow/snowplow-ruby-tracker#138]
The Tracker's `track_x_event` methods allow the addition of contextual data, in the form of self-describing JSON entities. Currently, the entities must be attached to an event as an array, even if there is only one entity. This adds complexity and could cause a mistake as it is not intuitive.

Allow single entities to be provided. This would bring the `context` parameter in line with `emitters` in Tracker initialisation - either a single Emitter or array of Emitters is permitted.

**Comment by paulboocock** [comment]
No harm in doing this since ruby is dynamic, but this deviates from all other trackers. It's the common approach to pass context as an array, even if there is just one. 

I wonder if consistency across trackers is better than improving the API for this single tracker. One could argue that a parameter which can be either an object or an array, is actually more complex than it always being an array.

**Comment by mscwilson** [comment]
Interesting. I take your point about complexity!
I forgot that typed languages exist. So most of the trackers only allow one Emitter to be added to a new Tracker object, not one/a list of Emitters.

**Comment by paulboocock** [comment]
The other trackers all only accept a list of emitters. Given Rubys flexibility and the way emitters currently work, I'm not adverse to this change just pointing out the slight differences this would make to the strongly typed languages. I think it'll depend how much boilerplate it adds to each track call as to whether it seems worth the maintenance, as a bar minimum it's gonna need a few new tests adding :-)

**Comment by mscwilson** [comment]
I've decided not to make this change - I spotted that items in an ecommerce transaction also have to be an array, so context entities are not the odd one out.
