### ISSUE TITLE
Ruby 3.0 compatibility with v0.7.0

### ISSUE THREAD

**Issue by schm** [snowplow/snowplow-ruby-tracker#154]
**Describe the bug**

With the release of v0.7.0, we're running into compatibility issues with Ruby 3.0.2. Previous versions of the gem worked flawlessly with 3.0.

**To Reproduce**

Using this sample script (copied and adapted from the documentation)

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'snowplow-tracker'
end

initial_subject = SnowplowTracker::Subject.new
emitter = SnowplowTracker::Emitter.new(endpoint: "d3rkrsqld9gmqf.cloudfront.net")
tracker = SnowplowTracker::Tracker.new(emitters: [emitter], subject: initial_subject, namespace: 'cf', app_id: 'ID-ap00035', encode_base64: false)
```

The script works as expected in Ruby 2.7.4. In Ruby 3.0.2 however it raises an error related to the method signature

```
/Users/schmidt/.rvm/gems/ruby-3.0.2/gems/snowplow-tracker-0.7.0/lib/snowplow-tracker/emitters.rb:142:in `initialize': wrong number of arguments (given 1, expected 0; required keyword: endpoint) (ArgumentError)
	from /Users/schmidt/.rvm/gems/ruby-3.0.2/gems/contracts-0.16.1/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/schmidt/.rvm/gems/ruby-3.0.2/gems/contracts-0.16.1/lib/contracts/call_with.rb:87:in `call_with_inner'
	from /Users/schmidt/.rvm/gems/ruby-3.0.2/gems/contracts-0.16.1/lib/contracts/method_handler.rb:133:in `block (2 levels) in redefine_method'
	from /Users/schmidt/.rvm/gems/ruby-3.0.2/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `each'
	from /Users/schmidt/.rvm/gems/ruby-3.0.2/gems/contracts-0.16.1/lib/contracts/method_handler.rb:132:in `block in redefine_method'
	from snowplow.rb:10:in `new'
	from snowplow.rb:10:in `<main>'
```

**Expected behavior**

I would like to have a way to use v0.7.0 with Ruby 3.0.2. Similar to how it used to work.

**Screenshots**

<img width="1129" alt="Screen Shot 2021-10-20 at 10 22 39" src="https://user-images.githubusercontent.com/1830847/138055988-260b69b3-40d2-49af-a520-18283f2b2148.png">

**Environment (please complete the following information):**
 - OS: macOS, but unfortunately we've also seen the problem on production, which is based on the official ruby 3.0.2 docker image (which is running some kind of GNU/Linux)
 - Ruby version 3.0.2
 - Gem version 0.7.0

**Additional context**

I suspect this was introduced with  #135. It might be fixed with contracts 0.17 which includes https://github.com/egonSchiele/contracts.ruby/pull/295

**Comment by mscwilson** [comment]
The problem is with RubyGems, which doesn't allow for conditional dependencies in the gemspec. The contracts versioning works fine with locally built tracker gems.

We are going to remove contracts as a dependency, which will fix this issue. I hope to release the new version towards the end of next week. Sorry again for the inconvenience and thanks for letting us know.

**Comment by mscwilson** [comment]
Hi @schm and @sahilbathla, we are happy to announce Ruby tracker version 0.8.0.

[Here's the release announcement](https://discourse.snowplowanalytics.com/t/snowplow-ruby-tracker-0-8-0-released/5859) on our Discourse forums, which discusses the changes since 0.6.0.

Thanks again for getting in touch. We hope you enjoy the revamped Ruby tracker!

**Comment by schm** [comment]
@mscwilson thanks for the write-up and your quick work. 💚 

Dependabot was already kind enough to create a new PR for our project and I'll update our code to the new APIs soon. 👍
